name: Deploy Proto & NPM publish

on:
  pull_request_target:
    types: [opened, edited, synchronize]
    branches: [ master ]

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  NPM_VERSION: patch


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3.0.0
      with:
        ref: master
        repository: furya-network/furya
        path: furya

    - name: Checkout destination repository
      uses: actions/checkout@v3.0.0
      with:
        ref: master
        repository: ${{ secrets.ST_REPO }}/furyajs
        path: furyajs
        token: ${{ secrets.ST_TOKEN }}

    - name: Copy Proto Files
      run: |
        cp -r furya/proto/furya furyajs/proto
        git -C furyajs add .
        git -C furyajs status
        git -C furyajs config user.email "action@github.com"
        git -C furyajs config user.name "GitHub Action"
        git -C furyajs commit --allow-empty -am "Proto Deployment [skip ci]"

    - name: Npm Install
      run: |
        echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > furyajs/.npmrc
        npm install --prefix furyajs
        git -C furyajs checkout .

    - name: Delete src/codegen and types
      run: |
        rm -rf furyajs/src/codegen
        rm -rf furyajs/types

    - name: Npm Run Codegen
      run: |
        npm run codegen --prefix furyajs

    - name: Commit changes
      run: |
        git -C furyajs add .
        git -C furyajs config user.email "action@github.com"
        git -C furyajs config user.name "GitHub Action"
        git -C furyajs commit --allow-empty -am "Codegen Deployment [skip ci]"

    - name: Determine NPM version
      run: |
        cd furyajs
        if [[ "${{ github.event.pull_request.title }}" == *"major"* ]]; then
          echo "NPM_VERSION=major" >> $GITHUB_ENV
        elif [[ "${{ github.event.pull_request.title }}" == *"minor"* ]]; then
          echo "NPM_VERSION=minor" >> $GITHUB_ENV
        elif [[ "${{ github.event.pull_request.title }}" == *"patch"* ]]; then
          echo "NPM_VERSION=patch" >> $GITHUB_ENV
        fi

    - name: Bump NPM version
      run: |
        cd furyajs
        git status
        if [ "${{ env.NPM_VERSION }}" == "major" ]; then
          npm version major
        elif [ "${{ env.NPM_VERSION }}" == "minor" ]; then
          npm version minor
        elif [ "${{ env.NPM_VERSION }}" == "patch" ]; then
          npm version patch
        fi
        git status

    - name: Push furyajs
      run: git -C furyajs push

    - name: Publish NPM Package
      run: |
        echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > furyajs/.npmrc
        cat furyajs/.npmrc
        cd furyajs
        ls -la
        npm publish --access=restricted --force
